version: "3.8"

services:
  identity:
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    volumes:
      - ./identity/realm-export.json:/opt/keycloak/data/import/realm-export.json